export const COMMON_LEGAL_KEYWORDS = [
  "ART.", "KPW", "KPC", "KC", "PRZEDAWNIENIE", "REKLAMACJA", 
  "ZWROT", "TERMIN", "ZAWITY", "SĄD", "WEZWANIE", "USTAWA", 
  "ODSTĄPIENIE", "RODO", "UMOWA", "KLAUZULA", "ABUZYWNA",
  "PARAGRAF", "§", "WYROK", "NAKAZ", "ZAPŁATY", "DŁUG",
  "WINDYKACJA", "KOMORNIK", "INTERES", "PRAWNY", "BŁĄD FORMALNY",
  "UMORZENIE", "ODRZUCENIE ROSZCZENIA", "BEZPODSTAWNE"
];